config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: "users/sessions",
  }
  root to: "games#index"
  
  resources :sentences

  resources :results, only: [:index, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/result.rb
class Result < ApplicationRecord
  belongs_to :user
end

app/models/sentence.rb
class Sentence < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, authentication_keys: [:nickname]

  has_many :sentences
  has_many :results

  def email_required?
    false
  end

  def email_changed?
    false
  end

  def will_save_change_to_email?
    false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:nickname])
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
    @sentences = Sentence.all.shuffle
    gon.sentences = @sentences

    if user_signed_in?
      @sentences_myself = Sentence.where(user_id: current_user.id).shuffle
      gon.sentences_myself = @sentences_myself
    end

    @result = Result.new
  end
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  def index
    @results = Result.all.order("average desc")
  end

  def create
    @result = Result.new(set_result)
    if @result.save
      redirect_to results_path
    end
  end

  private
  def set_result
    params.require(:result).permit(:stc_num, :string_num, :average, :user_id)
  end
end

app/controllers/sentences_controller.rb
class SentencesController < ApplicationController
  before_action :get_sentence, only: [:edit, :update, :destroy]

  def index
    @sentences = Sentence.all
  end

  def new
    @sentences = Sentence.new
  end

  def create
    @sentence = Sentence.new(set_sentence)
    if @sentence.save
      redirect_to sentences_path
    end
  end

  def edit
  end

  def update
    if @sentence.update(set_sentence)
      redirect_to sentences_path
    end
  end

  def destroy
    if @sentence.destroy
      redirect_to sentences_path
    end
  end

  private
  def set_sentence
    params.require(:sentence).permit(:text, :romaji).merge(user_id: current_user.id)
  end
  
  def get_sentence
    @sentence = Sentence.find(params[:id])
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/helpers/sentences_helper.rb
module SentencesHelper
end

app/views/games/_games-result.html.haml
.result.dsp-none
  %br
  .result__clear
    全問クリア！
  %br
  %table
    %tr
      %th
        文章数
      %td.result__stc-num
        
    %tr
      %th
        合計入力文字数
      %td.result__stc-str-num
        
    %tr
      %th
        タイム
      %td.result__time
        
    %tr
      %th
        文字数 / 秒
      %td.result__average

  %br
  .result__wrapper
    = link_to "再チャレンジ！", root_path, class: "result__wrapper__challenge"
    - if user_signed_in?
      -# resultテーブル 隠しデータ項目
      = form_with model: @result, url: results_path, method: :post, local: true do |f|
        = f.hidden_field :stc_num, value: 0, class: "hidden-stc_num"
        = f.hidden_field :string_num, value: 0, class: "hidden-string_num"
        = f.hidden_field :average, value: 0.0, class: "hidden-average"
        = f.hidden_field :user_id, value: current_user.id, class: "hidden-user_id"
        = f.submit "結果を登録する", class: "result__wrapper__register"
  %br
  - if !user_signed_in?
    .result__note
      ユーザー登録を行うと結果を記録することができます。

app/views/games/index.html.haml
= javascript_include_tag "games"

.wrapper
  .title
    タイピング　練習
  .header
    .header__register
      - if user_signed_in?
        - path = sentences_path
      - else
        - path = new_user_session_path
      = link_to path do
        文章登録
    .header__wrapper
      .header__wrapper--deco
        = link_to results_path, class: "deco-link" do
          ランキング
      - if user_signed_in?
        .header__wrapper--deco
          = link_to destroy_user_session_path, method: :delete, class: "deco-link", data: {confirm: "ログアウトしてもよろしいですか？"} do
            ログアウト
      - else
        .header__wrapper--deco
          = link_to new_user_registration_path, class: "deco-link" do
            ユーザー新規登録
        .header__wrapper--deco
          = link_to new_user_session_path, class: "deco-link" do
            ログイン
  - if !user_signed_in?
    .register-note
      文章登録をする場合は、ログインをしてください。


  = render "games-result"

  .games
    .games__target-stc
      - if user_signed_in?
        .games__target-stc--all
          = label_tag "target_1", "すべての文章"
          = radio_button_tag "target", 1, checked: "checked"
        .games__target-stc--myself
          = label_tag "target_2", "自分が作成した文章のみ"
          = radio_button_tag "target", 2
      - else
        .games__target-stc--all.games-none
          = radio_button_tag "target", 1, checked: "checked"

        
    .games__num
      挑戦する文章の数を入力してください。
      %br
      .games__num--all
        - num_all = []
        - @sentences.length.times do |i|
          - num_all << i + 1
        = select_tag "select", options_for_select(num_all), class: "select-all"
      - if user_signed_in?
        .games__num--myself.myself-none
          - num_myself = []
          - @sentences_myself.length.times do |i|
            - num_myself << i + 1
          = select_tag "select", options_for_select(num_myself), class: "select-myself"

    .games__start
      %p
        スタートをクリックするとゲーム・測定開始！
      .games__start__note
        ※必ず半角で入力をしてください。
      .games__start__btn
        start!
    .games__sentences
      %p
        ここに問題文が出力されます。
      .games__sentences__text
        = text_field_tag "text", "", class: "input-field"
      .no-display
    .dummy
  %br

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Typing
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = include_gon
  %body
    = yield

app/views/results/index.html.haml
.wrapper
  .ranking-header
    ランキング一覧
  .header-wrapper
    .dummy
    .header-wrapper__result-top
      = link_to "トップ画面に戻る", root_path

  .ranking
    %table
      %tr
        %th 順位
        %th 名前
        %th 文章数
        %th 入力文字数
        %th 入力文字数 / 秒
        %th 日時
      - @results.each_with_index do |result, i|
        %tr
          %td
            = i + 1
          %td
            = result.user.nickname
          %td
            = result.stc_num
          %td
            = result.string_num
          %td
            = result.average
          %td
            = result.created_at.strftime("%Y-%m-%d %H:%M")

    %br

app/views/sentences/_header.html.haml
.stc-header
  .dummy
  .header-title
    - if request.fullpath.include?("new")
      追　加　登　録
    - elsif request.fullpath.include?("edit")
      編　集

  %ul
    %li
      - if request.fullpath == "/sentences"
        = link_to new_sentence_path do
          追加登録
      - else
        = link_to sentences_path do
          戻る

    %li
      = link_to root_path do
        トップ画面

app/views/sentences/_input_sentence.html.haml
.stc-field
  - if request.fullpath.include?("new")
    - form_obj = @sentences
    - method = "post"
  - else
    - form_obj = @sentence
    - method = "patch"
  = form_with model: form_obj, method: method, local: true do |f|
    .dummy
    .stc-field__wrapper
      .stc-field__note
        好きな文章を入力してください。
      .stc-field__input
        = f.text_area :text, class: "stc-field__input--text"
      .stc-field__input
        .stc-field__input--btn
          ローマ字変換
        -# %p
        -#   ボタンを押すと、下記エリアに、ローマ字が入力されます。
        -# %p 必要であれば、修正してください。
        %br
        %p
          下記欄にローマ字を入力してください。
        = f.text_area :romaji, class: "stc-field__input--text"
      .stc-field__submit
        - if request.fullpath.include?("new")
          - str = "登録する"
        - else
          - str = "編集する"
        = f.submit str, class: "submit-btn"
    .dummy

app/views/sentences/edit.html.haml
.wrapper
  = render "header"

  = render "input_sentence"

app/views/sentences/index.html.haml
= javascript_include_tag "stc_index"

.wrapper
  = render "header"

  .stc-tab
    .stc-tab__wrapper
      .stc-tab__wrapper--myself.color
        自分の登録した文章
      .stc-tab__wrapper--all
        全ての文章

    .stc-myself
      .stc
        - @sentences.each do |sentence|
          - if sentence.user_id === current_user.id
            .stc__wrapper
              .stc__wrapper--id
                = sentence.id
              .stc__wrapper__btn
                = link_to edit_sentence_path(sentence.id), class: "stc__wrapper__btn--edit" do
                  編集
              .stc__wrapper__btn
                = link_to sentence_path(sentence.id), method: :delete, data: {confirm: "削除してもよろしいですか？"}, class: "stc__wrapper__btn--des" do
                  削除
            %table
              %tr
                %th 日本語
                %td
                  = sentence.text
              %tr
                %th ローマ字
                %td
                  = sentence.romaji
            %br

    .stc-all.stc-none
      .stc
        - @sentences.each do |sentence|
          .stc__wrapper
            .stc__wrapper--id
              = sentence.id
            - if sentence.user_id === current_user.id
              .stc__wrapper__btn
                = link_to edit_sentence_path(sentence.id), class: "stc__wrapper__btn--edit" do
                  編集
              .stc__wrapper__btn
                = link_to sentence_path(sentence.id), method: :delete, data: {confirm: "削除してもよろしいですか？"}, class: "stc__wrapper__btn--des" do
                  削除
          %table
            %tr
              %th 日本語
              %td
                = sentence.text
            %tr
              %th ローマ字
              %td
                = sentence.romaji
          %br
  .dummy

app/views/sentences/new.html.haml
.wrapper
  = render "header"

  .stc-field
    = form_with model: @sentences do |f|
      .dummy
      .wrapper
        .stc-field__note
          好きな文章を入力してください。
        .stc-field__input
          = f.text_area :text, class: "stc-field__input--text"
        .stc-field__input
          .stc-field__input--btn
            ローマ字変換
          %p ボタンを押すと、下記エリアに、ローマ字が入力されます。
          %p 必要であれば、修正してください。
          = f.text_area :romaji, class: "stc-field__input--text"
        .stc-field__submit
          = f.submit "登録する", class: "submit-btn"
      .dummy

app/views/users/shared/_error_messages.html.haml
- if resource.errors.any?
  #error_explanation
    %h2
      = I18n.t("errors.messages.not_saved",                 |
        count: resource.errors.count,                       |
        resource: resource.class.model_name.human.downcase) |
    %ul
      - resource.errors.full_messages.each do |message|
        %li= message

app/views/users/shared/_links.html.haml
- if controller_name != 'sessions'
  = link_to "Log in", new_session_path(resource_name)
  %br/
- if devise_mapping.registerable? && controller_name != 'registrations'
  = link_to "Sign up", new_registration_path(resource_name)
  %br/
- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations'
  = link_to "Forgot your password?", new_password_path(resource_name)
  %br/
- if devise_mapping.confirmable? && controller_name != 'confirmations'
  = link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name)
  %br/
- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks'
  = link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name)
  %br/
- if devise_mapping.omniauthable?
  - resource_class.omniauth_providers.each do |provider|
    = link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider)
    %br/

app/views/users/shared/_user-header.html.haml
.user-header
  .user-header__title
    - if request.fullpath.include?("sign_up")
      ユーザー新規登録
    -# - else
    -#   ログイン
  .user-header__wrapper
    .dummy
    .user-top
      = link_to "トップ画面へ戻る", root_path